using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NET_Project
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(x => x.EnableEndpointRouting = false);  //Adds MVC services to project
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseDeveloperExceptionPage(); //Provides details if there is a server error
            app.UseDefaultFiles(); //uses index.html in wwwroot as default page
            app.UseStaticFiles(); //makes wwwroot files accessible to public

            app.UseMvcWithDefaultRoute(); //Uses MVC default route: {controller = Home} {action = Index}{id?}

            //app.Use will execute if file path is not publicly accessible within wwwroot
            app.Use(async (context, next) =>
            {
                await context.Response.WriteAsync("This text was generated by the app.Use middleware. Request path \"" + context.Request.Path.Value + "\"  is unavailable.\n");
                await next.Invoke();
            });

            //app.Run will execute following app.Use
            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("Your request did not match any configured route.");
            });

        }
    }
}
